services:
  mysql:
    build:
      context: ./Backend
      dockerfile: Dockerfile.mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3306:3306"
    restart: always
    networks:
      - ecommerce_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 123456789
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - mysql
    networks:
      - ecommerce_net

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "5001:5001"
    env_file:
      - ./Backend/.env
    restart: always
    depends_on:
      - mysql
    networks:
      - ecommerce_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "5000:5000"
    env_file:
      - ./frontend/.env
    restart: always
    depends_on:
      - backend
    networks:
      - ecommerce_net

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - ecommerce_net

networks:
  ecommerce_net:
    driver: bridge
